/*
 * Copyright (c) 2026 Chris7X
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */
package org.meshtastic.feature.voiceburst.repository

import android.content.Context
import androidx.datastore.core.DataStore
import androidx.datastore.preferences.core.Preferences
import androidx.datastore.preferences.core.booleanPreferencesKey
import androidx.datastore.preferences.core.edit
import co.touchlab.kermit.Logger
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.MutableSharedFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.filter
import kotlinx.coroutines.flow.launchIn
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.onEach
import kotlinx.coroutines.flow.stateIn
import okio.ByteString.Companion.toByteString
import org.meshtastic.core.common.util.nowMillis
import org.meshtastic.core.model.DataPacket
import org.meshtastic.core.model.MessageStatus
import org.meshtastic.core.model.RadioController
import org.meshtastic.core.repository.NodeRepository
import org.meshtastic.core.repository.PacketRepository
import org.meshtastic.core.repository.ServiceRepository
import org.meshtastic.feature.voiceburst.model.VoiceBurstPayload
import org.meshtastic.proto.PortNum
import java.io.File

private const val TAG = "AndroidVoiceBurstRepository"

/**
 * Android implementation of [VoiceBurstRepository].
 *
 * Audio persistence architecture (WhatsApp/Telegram style):
 *   - Each received burst is saved as a file <filesDir>/voice_bursts/<packetId>.c2
 *   - The relative path ("voice_bursts/<id>.c2") is inserted in Message.audioFilePath
 *   - The UI resolves the absolute path via context.filesDir at playback time
 *   - The file persists until the user deletes the chat or clears the cache
 *
 * Sent bursts are also saved (the sender can replay their own message).
 */
class AndroidVoiceBurstRepository(
    private val radioController: RadioController,
    private val dataStore: DataStore<Preferences>,
    private val packetRepository: PacketRepository,
    private val nodeRepository: NodeRepository,
    private val serviceRepository: ServiceRepository,
    private val context: Context,
    private val scope: kotlinx.coroutines.CoroutineScope,
) : VoiceBurstRepository {

    /** Directory where .c2 files are saved: <filesDir>/voice_bursts/ */
    private val voiceBurstsDir: File by lazy {
        File(context.filesDir, "voice_bursts").also { it.mkdirs() }
    }

    // ─── Feature flag ─────────────────────────────────────────────────────────

    private val featureEnabledFlow = dataStore.data
        .map { prefs -> prefs[KEY_FEATURE_ENABLED] ?: false }

    override val isFeatureEnabled: StateFlow<Boolean> =
        featureEnabledFlow.stateIn(
            scope = scope,
            started = kotlinx.coroutines.flow.SharingStarted.Eagerly,
            initialValue = false,
        )

    override suspend fun setFeatureEnabled(enabled: Boolean) {
        dataStore.edit { prefs -> prefs[KEY_FEATURE_ENABLED] = enabled }
        Logger.i(TAG) { "Voice Burst feature: ${if (enabled) "enabled" else "disabled"}" }
    }

    // ─── Send ─────────────────────────────────────────────────────────────────

    override suspend fun sendBurst(payload: VoiceBurstPayload, contactKey: String): Boolean {
        val channelDigit = contactKey.firstOrNull()?.digitToIntOrNull()
        val destNodeId = if (channelDigit != null) contactKey.substring(1) else contactKey

        return try {
            val ourNode = nodeRepository.ourNodeInfo.value
            val fromId = ourNode?.user?.id ?: DataPacket.ID_LOCAL
            val myNodeNum = ourNode?.num ?: 0

            val packet = DataPacket(
                to = destNodeId,
                bytes = payload.encode().toByteString(),
                dataType = VoiceBurstPayload.PORT_NUM,
                from = fromId,
                channel = channelDigit ?: DataPacket.PKC_CHANNEL_INDEX,
                wantAck = true,
                status = MessageStatus.ENROUTE,
            )

            // 1. Save to DB (appears in chat immediately)
            packetRepository.savePacket(
                myNodeNum = myNodeNum,
                contactKey = contactKey,
                packet = packet,
                receivedTime = nowMillis,
                read = true,
            )

            // 2. Save audio bytes to disk (sender can replay)
            // Use the packetId generated by the DB for the file name
            val savedPacket = packetRepository.findPacketsWithId(packet.id).firstOrNull()
            val packetId = savedPacket?.id ?: packet.id
            if (packetId != 0) {
                saveAudioFile(packetId, payload.audioData)
            }

            // 3. Send via radio
            radioController.sendMessage(packet)
            Logger.i(TAG) { "Burst sent to $destNodeId: ${payload.audioData.size} audio bytes" }
            true
        } catch (e: Exception) {
            Logger.e(TAG, e) { "Error sending burst to $destNodeId (contactKey=$contactKey)" }
            false
        }
    }

    // ─── Receive ────────────────────────────────────────────────────────────

    private val _incomingBursts = MutableSharedFlow<VoiceBurstPayload>(replay = 0, extraBufferCapacity = 8)
    override val incomingBursts: Flow<VoiceBurstPayload> = _incomingBursts

    init {
        serviceRepository.meshPacketFlow
            .filter { it.decoded?.portnum == PortNum.PRIVATE_APP }
            .onEach { packet -> processIncomingBurst(packet) }
            .launchIn(scope)
    }

    private suspend fun processIncomingBurst(packet: org.meshtastic.proto.MeshPacket) {
        val decoded = packet.decoded ?: return
        val payloadBytes = decoded.payload.toByteArray()

        val payload = VoiceBurstPayload.decode(payloadBytes)
        if (payload == null) {
            Logger.w(TAG) { "Invalid payload from ${packet.from} (${payloadBytes.size} bytes)" }
            return
        }

        Logger.i(TAG) { "Burst received from ${packet.from}: ${payload.durationMs}ms, ${payload.audioData.size} bytes" }

        val ourNode = nodeRepository.ourNodeInfo.value
        val myNodeNum = ourNode?.num ?: 0
        val fromId = DataPacket.nodeNumToDefaultId(packet.from)
        val toId = if (packet.to < 0 || packet.to == DataPacket.NODENUM_BROADCAST) {
            DataPacket.ID_BROADCAST
        } else {
            DataPacket.nodeNumToDefaultId(packet.to)
        }

        val channelIndex = if (packet.pki_encrypted == true) DataPacket.PKC_CHANNEL_INDEX else packet.channel
        val contactKey = "${channelIndex}${fromId}"

        val dataPacket = DataPacket(
            to = toId,
            bytes = payloadBytes.toByteString(),
            dataType = VoiceBurstPayload.PORT_NUM,
            from = fromId,
            time = nowMillis,
            id = packet.id,
            status = MessageStatus.RECEIVED,
            channel = channelIndex,
            wantAck = false,
            snr = packet.rx_snr,
            rssi = packet.rx_rssi,
        )

        try {
            // Deduplicate
            if (packetRepository.findPacketsWithId(packet.id).isNotEmpty()) {
                Logger.d(TAG) { "Duplicate burst ignored: packetId=${packet.id}" }
                return
            }

            // Save to DB → chat bubble
            packetRepository.savePacket(
                myNodeNum = myNodeNum,
                contactKey = contactKey,
                packet = dataPacket,
                receivedTime = nowMillis,
                read = false,
            )

            // Save audio to disk — the file name matches the packetId
            // so that Message.audioFilePath = "voice_bursts/<packetId>.c2" points to the file
            saveAudioFile(packet.id, payload.audioData)
            Logger.i(TAG) { "Burst saved: contactKey=$contactKey file=voice_bursts/${packet.id}.c2" }

        } catch (e: Exception) {
            Logger.e(TAG, e) { "Error saving burst from ${packet.from}" }
        }

        // Emit for immediate playback (autoplay on arrival)
        _incomingBursts.tryEmit(payload.copy(senderNodeId = fromId))
    }

    // ─── Audio file I/O ───────────────────────────────────────────────────────

    /**
     * Saves the compressed Codec2 bytes to a .c2 file.
     * The file can be read later to replay the message.
     */
    private fun saveAudioFile(packetId: Int, audioData: ByteArray) {
        try {
            val file = File(voiceBurstsDir, "$packetId.c2")
            file.writeBytes(audioData)
            Logger.d(TAG) { "Audio saved: ${file.absolutePath} (${audioData.size} bytes)" }
        } catch (e: Exception) {
            Logger.e(TAG, e) { "Error writing audio file for packetId=$packetId" }
        }
    }

    /**
     * Reads the Codec2 bytes from disk given a relative path.
     * Used by the ViewModel to play a saved voice message.
     *
     * @param relativePath e.g. "voice_bursts/12345678.c2"
     * @return ByteArray with the Codec2 bytes, or null if the file does not exist
     */
    override fun readAudioFile(relativePath: String): ByteArray? {
        return try {
            val file = File(context.filesDir, relativePath)
            if (file.exists()) file.readBytes() else null
        } catch (e: Exception) {
            Logger.e(TAG, e) { "Error reading audio file: $relativePath" }
            null
        }
    }

    companion object {
        private val KEY_FEATURE_ENABLED = booleanPreferencesKey("voice_burst_feature_enabled")
    }
}
